kakao-tech-campus-2nd-step3/Team21_BE

build.gradle, src/main/java/com/potatocake/everymoment/config/JpaAuditingConfig.java, src/main/java/com/potatocake/everymoment/config/SecurityConfig.java, src/main/java/com/potatocake/everymoment/constant/Constants.java, src/main/java/com/potatocake/everymoment/dto/SuccessResponse.java, src/main/java/com/potatocake/everymoment/dto/request/MemberLoginRequest.java, src/main/java/com/potatocake/everymoment/dto/response/JwtResponse.java, src/main/java/com/potatocake/everymoment/entity/Member.java, src/main/java/com/potatocake/everymoment/exception/ErrorCode.java, src/main/java/com/potatocake/everymoment/exception/GlobalExceptionHandler.java, src/main/java/com/potatocake/everymoment/exception/ValidationErrorMessage.java, src/main/java/com/potatocake/everymoment/repository/MemberRepository.java, src/main/java/com/potatocake/everymoment/security/MemberAuthenticationService.java, src/main/java/com/potatocake/everymoment/security/MemberDetails.java, src/main/java/com/potatocake/everymoment/security/filter/JwtFilter.java, src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java, src/main/java/com/potatocake/everymoment/security/handler/Http401Handler.java, src/main/java/com/potatocake/everymoment/util/JwtUtil.java
JWT를 사용하여 회원가입 및 로그인 구현했습니다.
회원가입 API를 따로 두지 않고, 로그인 API만 두어 회원가입 및 로그인을 동시에 처리하였습니다.
이미 존재하는 유저라면 로그인(JWT 발급)만 처리, 존재하지 않는다면 회원가입 및 로그인 같이 진행하였습니다.
그리고 JWT 필터를 두어 로그인 이후 모든 요청은 이 필터를 거치게 구현했습니다.
이 필터에서는 헤더로 넘어온 JWT를 검증합니다.
close #7
=> feat: 회원가입 및 로그인 구현

.github/workflows/master_cicd.yml, .github/workflows/pr_weekly_ci.yml, .gitignore, build.gradle, src/main/java/com/potatocake/everymoment/config/AwsS3Properties.java, src/main/java/com/potatocake/everymoment/config/SecurityConfig.java, src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/java/com/potatocake/everymoment/dto/SuccessResponse.java, src/main/java/com/potatocake/everymoment/dto/response/MemberDetailResponse.java, src/main/java/com/potatocake/everymoment/dto/response/MemberResponse.java, src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResponse.java, src/main/java/com/potatocake/everymoment/entity/Member.java, src/main/java/com/potatocake/everymoment/exception/ErrorCode.java, src/main/java/com/potatocake/everymoment/exception/GlobalExceptionHandler.java, src/main/java/com/potatocake/everymoment/repository/MemberRepository.java, src/main/java/com/potatocake/everymoment/security/MemberDetails.java, src/main/java/com/potatocake/everymoment/security/filter/JwtFilter.java, src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java, src/main/java/com/potatocake/everymoment/service/MemberService.java, src/main/java/com/potatocake/everymoment/util/PagingUtil.java, src/main/java/com/potatocake/everymoment/util/S3FileUploader.java, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java, src/test/java/com/potatocake/everymoment/repository/MemberRepositoryTest.java, src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java, src/test/java/com/potatocake/everymoment/util/PagingUtilTest.java
* 회원 검색 API
* 내 정보 조회 API
* 특정 회원 정보 조회 API
* 회원 정보 수정 API
* 회원 컨트롤러/서비스/리파지토리 및 `PagingUtil` 테스트 코드 작성
* 자동 CI 테스트 및 실패 지점까지 자동으로 코멘트
* 기존 CI/CD 자동 배포와는 다른 파일로 분리
현재 SuccessResponse 생성 코드가 너무 반복되고 있어, 메서드 추가해 두었습니다.
**`code`** 가 200이 아니고 **`info`** 응답이 필요하다면 맨 위 메서드,
**`code`** 가 200이고, **`info`** 응답이 필요하다면 가운데 메서드, 필요 없다면 아래 메서드를 사용해 주시면 됩니다!
파일은 이렇게 dev와 prod(운영) 환경으로 나눴습니다
dev에는 민감한 정보도 담겨 있어서 .gitignore에 등록해두었습니다
기존 `application.yml`은 제거해 주시고, 아래와 같이 `application-dev.yml`을 따로 만들어 주세요!
```yaml
spring:
datasource:
url: jdbc:h2:mem:testdb
username: sa
password:
jpa:
properties:
hibernate:
format_sql: true
show-sql: true
h2:
console:
enabled: true
aws:
s3:
client: AmazonS3
region: ap-northeast-2
bucket: secret
accessKey: secret
secretKey: secret
```
secret에 관한 정보는 따로 드리겠습니다!
그리고, 기본 액티브 …
=> feat: 회원 관련 API 구현 및 CI 관련 워크플로우 추가

.github/workflows/master_weekly_cicd.yml, src/main/java/com/potatocake/everymoment/exception/ErrorCode.java
* 이미 존재하는 enum 제거
* weekly 브랜치 병합 시에도 CI/CD 워크플로우 동작
close #22
=> feat: 중복된 enum 제거 및 weekly 브랜치 병합 시 CI/CD 트리거 추가

.github/workflows/master_weekly_cicd.yml, src/main/java/com/potatocake/everymoment/config/SwaggerConfig.java, src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/java/com/potatocake/everymoment/exception/ErrorCode.java, src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java
* JWT 인증을 포함하여 API 테스트를 할 수 있도록 Swagger 설정
* POST로만 로그인 요청이 가능하도록 수정
close #28
=> feat: Swagger 설정 및 로그인 HttpMethod 설정

src/main/java/com/potatocake/everymoment/controller/CategoryController.java, src/main/java/com/potatocake/everymoment/dto/request/CategoryCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/response/CategoryResponse.java, src/main/java/com/potatocake/everymoment/entity/Category.java, src/main/java/com/potatocake/everymoment/exception/ErrorCode.java, src/main/java/com/potatocake/everymoment/exception/ErrorResponse.java, src/main/java/com/potatocake/everymoment/repository/CategoryRepository.java, src/main/java/com/potatocake/everymoment/service/CategoryService.java
카테고리 관련 API 구현
* 카테고리 조회 API
* 카테고리 추가 API
* 카테고리 수정 API
* 카테고리 삭제 API
close #31
=> feat: 카테고리 API 구현

src/main/java/com/potatocake/everymoment/controller/FriendRequestController.java, src/main/java/com/potatocake/everymoment/controller/LikeController.java, src/main/java/com/potatocake/everymoment/dto/response/FriendRequestPageRequest.java, src/main/java/com/potatocake/everymoment/dto/response/FriendRequestResponse.java, src/main/java/com/potatocake/everymoment/dto/response/LikeCountResponse.java, src/main/java/com/potatocake/everymoment/entity/FriendRequest.java, src/main/java/com/potatocake/everymoment/entity/Like.java, src/main/java/com/potatocake/everymoment/exception/ErrorCode.java, src/main/java/com/potatocake/everymoment/repository/FriendRepository.java, src/main/java/com/potatocake/everymoment/repository/FriendRequestRepository.java, src/main/java/com/potatocake/everymoment/repository/LikeRepository.java, src/main/java/com/potatocake/everymoment/service/FriendRequestService.java, src/main/java/com/potatocake/everymoment/service/LikeService.java, src/main/java/com/potatocake/everymoment/service/MemberService.java, src/main/java/com/potatocake/everymoment/util/IdExtractor.java, src/main/java/com/potatocake/everymoment/util/PagingUtil.java, src/test/java/com/potatocake/everymoment/util/PagingUtilTest.java
친구 추가 및 좋아요 관련 API 구현
* 친구 추가 요청 목록 조회 API
* 친구 추가 요청 API
* 친구 추가 수락 API
* 친구 추가 거절 API
* 좋아요 추가/삭제 (토글) API
* 특정 일기의 좋아요 수 조회 API 구현
close #34
=> feat: 친구 추가/좋아요 API 구현

src/main/java/com/potatocake/everymoment/controller/FriendController.java, src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/java/com/potatocake/everymoment/dto/request/MemberLoginRequest.java, src/main/java/com/potatocake/everymoment/dto/response/MemberDetailResponse.java, src/main/java/com/potatocake/everymoment/entity/Member.java, src/main/java/com/potatocake/everymoment/exception/ValidationErrorMessage.java, src/main/java/com/potatocake/everymoment/repository/MemberRepository.java, src/main/java/com/potatocake/everymoment/security/MemberAuthenticationService.java, src/main/java/com/potatocake/everymoment/security/MemberDetails.java, src/main/java/com/potatocake/everymoment/security/filter/LoginFilter.java, src/main/java/com/potatocake/everymoment/service/FriendService.java, src/main/java/com/potatocake/everymoment/service/FriendSpecification.java, src/main/java/com/potatocake/everymoment/service/MemberService.java, src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java, src/test/java/com/potatocake/everymoment/repository/MemberRepositoryTest.java, src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java
* 로그인 시 이메일 -> 회원 번호로 수정
* 회원 검색 시 닉네임으로만 검색 가능하도록 수정
* soft delete 방식으로 회원 탈퇴 API 구현
close #36
=> feat: 요구 사항 반영 및 회원 탈퇴 API 구현

src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/java/com/potatocake/everymoment/entity/Member.java, src/main/java/com/potatocake/everymoment/service/MemberService.java
회원 정보 수정 시 닉네임, 프로필 이미지를 입력 받는데, 둘 중 하나가 null일 경우에 대한 처리가 없어 에러 발생
* nickname 혹은 profileImage 둘 중 하나만 null인 경우에 대한 처리 추가
close #43
=> fix: 회원 정보 수정 API 에러 해결

src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/java/com/potatocake/everymoment/dto/response/FriendRequestStatus.java, src/main/java/com/potatocake/everymoment/dto/response/MemberMyResponse.java, src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResponse.java, src/main/java/com/potatocake/everymoment/dto/response/MemberSearchResultResponse.java, src/main/java/com/potatocake/everymoment/repository/FriendRepository.java, src/main/java/com/potatocake/everymoment/repository/FriendRequestRepository.java, src/main/java/com/potatocake/everymoment/service/MemberService.java, src/test/java/com/potatocake/everymoment/controller/MemberControllerTest.java, src/test/java/com/potatocake/everymoment/service/MemberServiceTest.java
로그인한 사용자를 기준으로 친구 요청 상태 응답에 추가
* **SELF:** 자기 자신
* **NONE:** 친구 미요청 상태
* **SENT:** 친구 요청을 보낸 상태
* **RECEIVED:** 친구 요청을 받은 상태
* **FRIEND:** 친구 상태
close #45
=> feat: 사용자 검색 시 친구 요청 상태 추가

.github/workflows/master_weekly_cicd.yml, src/main/java/com/potatocake/everymoment/controller/CategoryController.java, src/main/java/com/potatocake/everymoment/controller/CommentController.java, src/main/java/com/potatocake/everymoment/controller/DiaryController.java, src/main/java/com/potatocake/everymoment/controller/FileController.java, src/main/java/com/potatocake/everymoment/controller/FriendController.java, src/main/java/com/potatocake/everymoment/controller/FriendRequestController.java, src/main/java/com/potatocake/everymoment/controller/LikeController.java, src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/java/com/potatocake/everymoment/controller/NotificationController.java, src/main/resources/application-prod.yml
* 모든 컨트롤러에 Swagger 주석 추가
* 타임존 한국 시간대로 설정 (create_at, modify_at)
close #48
=> feat: Swagger API 문서에 설명 추가 및 타임존 설정

src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/response/FriendRequestResponse.java, src/main/java/com/potatocake/everymoment/entity/Diary.java, src/main/java/com/potatocake/everymoment/entity/DiaryCategory.java, src/main/java/com/potatocake/everymoment/service/DiaryService.java, src/main/java/com/potatocake/everymoment/service/DiarySpecification.java, src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java, src/main/java/com/potatocake/everymoment/service/FriendRequestService.java
* 친구 요청을 보낸 회원의 닉네임 및 프로필 이미지 응답 필드에 추가
close #55
=> feat: 친구 요청 목록 API에서 사용자 정보도 응답 필드에 추가

src/main/java/com/potatocake/everymoment/controller/FileController.java, src/main/java/com/potatocake/everymoment/dto/request/FileRequest.java, src/main/java/com/potatocake/everymoment/service/FileService.java
* 파일 업로드 및 수정 API의 request 필드에서 order 관련 정보 제거
close #57
=> feat: 파일 업로드 관련 API 수정

src/main/java/com/potatocake/everymoment/entity/Diary.java, src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java
* 친구 일기 조회 시 id 비교 에러 수정
* id끼리 비교해야 하는데, 엔티티와 id를 비교하여 에러 발생
close #61
=> fix: 친구 일기 조회 API 에러 수정

src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java, src/main/java/com/potatocake/everymoment/service/DiaryService.java, src/main/java/com/potatocake/everymoment/service/DiarySpecification.java
필터링 요소 없을 시
현재 날짜의 모든 일기 반환
필터링 요소 있을 시
모든 일기 중에 필터링 요소에 해당하는 것 반환
close #73
=> fix: 일기 필터링 오류 수정

src/main/java/com/potatocake/everymoment/controller/CommentController.java, src/main/java/com/potatocake/everymoment/controller/DiaryController.java, src/main/java/com/potatocake/everymoment/controller/FileController.java, src/main/java/com/potatocake/everymoment/dto/request/CategoryCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java, src/main/java/com/potatocake/everymoment/dto/request/FcmTokenRequest.java, src/main/java/com/potatocake/everymoment/entity/Comment.java, src/main/java/com/potatocake/everymoment/entity/DeviceToken.java, src/main/java/com/potatocake/everymoment/entity/Diary.java, src/main/java/com/potatocake/everymoment/entity/File.java, src/main/java/com/potatocake/everymoment/entity/Member.java, src/main/java/com/potatocake/everymoment/service/FileService.java
* 아무 파일도 첨부하지 않으면, 단순히 일기에 연관된 파일 모두 삭제
* 컬럼 최대 데이터 크기 지정
close #75
=> feat: 파일 수정 API에서 파일을 첨부하지 않아도 되도록 수정

src/main/java/com/potatocake/everymoment/controller/CommentController.java, src/main/java/com/potatocake/everymoment/controller/DiaryController.java, src/main/java/com/potatocake/everymoment/controller/FileController.java, src/main/java/com/potatocake/everymoment/dto/request/CategoryCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryFilterRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java, src/main/java/com/potatocake/everymoment/dto/request/FcmTokenRequest.java, src/main/java/com/potatocake/everymoment/entity/Comment.java, src/main/java/com/potatocake/everymoment/entity/DeviceToken.java, src/main/java/com/potatocake/everymoment/entity/Diary.java, src/main/java/com/potatocake/everymoment/entity/File.java, src/main/java/com/potatocake/everymoment/entity/Member.java, src/main/java/com/potatocake/everymoment/service/DiaryService.java, src/main/java/com/potatocake/everymoment/service/DiarySpecification.java, src/main/java/com/potatocake/everymoment/service/FileService.java
* 9주차 작업 master 브랜치에 반영
* weekly/9 -> master
#70 #73 #75
=> merge: 9주차 작업 master에 반영

src/main/java/com/potatocake/everymoment/config/SecurityConfig.java, src/main/java/com/potatocake/everymoment/config/SwaggerConfig.java, src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/java/com/potatocake/everymoment/dto/response/AnonymousLoginResponse.java, src/main/java/com/potatocake/everymoment/repository/MemberRepository.java, src/main/java/com/potatocake/everymoment/service/MemberService.java
=> feat: 익명 로그인 API 구현

src/main/java/com/potatocake/everymoment/controller/DiaryController.java, src/main/java/com/potatocake/everymoment/dto/request/CategoryRequest.java, src/main/java/com/potatocake/everymoment/dto/request/CommentRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryAutoCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/request/DiaryPatchRequest.java, src/main/java/com/potatocake/everymoment/dto/response/FriendDiaryResponse.java, src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java, src/main/java/com/potatocake/everymoment/repository/LikeRepository.java, src/main/java/com/potatocake/everymoment/service/DiaryService.java, src/main/java/com/potatocake/everymoment/service/FriendDiaryService.java, src/main/java/com/potatocake/everymoment/service/LikeService.java, src/main/resources/application-prod.yml, src/test/java/com/potatocake/everymoment/controller/DiaryControllerTest.java, src/test/java/com/potatocake/everymoment/entity/DiaryTest.java, src/test/java/com/potatocake/everymoment/repository/DiaryRepositoryTest.java, src/test/java/com/potatocake/everymoment/service/DiaryServiceTest.java
* 좋아요 상태 응답 필드 추가
* Diary 모든 계층 테스트 코드 작성 (컨트롤러/서비스/리파지토리/도메인)
close #89
=> feat: 일기에 대한 좋아요 상태 응답 필드 추가

.github/workflows/master_weekly_cicd.yml, .github/workflows/pr_weekly_ci.yml, src/main/java/com/potatocake/everymoment/util/JwtUtil.java, src/main/resources/application-prod.yml, src/test/java/com/potatocake/everymoment/controller/NotificationControllerTest.java, src/test/java/com/potatocake/everymoment/entity/NotificationTest.java, src/test/java/com/potatocake/everymoment/repository/NotificationRepositoryTest.java, src/test/java/com/potatocake/everymoment/service/NotificationServiceTest.java, src/test/java/com/potatocake/everymoment/util/IdExtractorTest.java, src/test/java/com/potatocake/everymoment/util/JwtUtilTest.java, src/test/java/com/potatocake/everymoment/util/PagingUtilTest.java, src/test/java/com/potatocake/everymoment/util/S3FileUploaderTest.java
* 분산 서버에서 JWT가 정상적으로 동작하지 않는 문제 해결
* A 서버에서 받은 토큰으로 B 서버에 요청하면 유효하지 않는 토큰
* SecretKey를 각 서버에서 임의로 생성해서 사용하기 때문에 발생
* 추가 테스트 코드 작성 (Notification 관련, Util 관련)
close #95
=> fix: JWT 인증 문제 해결 및 추가 테스트 코드 작성

src/main/java/com/potatocake/everymoment/controller/MemberController.java, src/main/resources/application-prod.yml
=> feat: 불필요한 로그 제거

src/main/java/com/potatocake/everymoment/dto/request/DiaryManualCreateRequest.java, src/main/java/com/potatocake/everymoment/dto/response/MyDiaryResponse.java, src/main/java/com/potatocake/everymoment/dto/response/MyDiarySimpleResponse.java, src/main/java/com/potatocake/everymoment/entity/Diary.java, src/main/java/com/potatocake/everymoment/repository/NotificationRepository.java, src/main/java/com/potatocake/everymoment/service/DiaryService.java, src/main/java/com/potatocake/everymoment/service/DiarySpecification.java, src/main/java/com/potatocake/everymoment/service/NotificationService.java, src/test/java/com/potatocake/everymoment/repository/NotificationRepositoryTest.java, src/test/java/com/potatocake/everymoment/service/NotificationServiceTest.java
수기 일기 카테고리 없이 저장안되는 오류 수정
수기 일기에 일기 날짜(diaryDate)추가
알림 최신순으로 변경
close #104
=> feat: 수기일기 수정, 알람 조회순 변경

src/main/java/com/potatocake/everymoment/entity/Like.java, src/main/java/com/potatocake/everymoment/repository/LikeRepository.java, src/main/java/com/potatocake/everymoment/service/LikeService.java
* 유니크 제약조건 추가 (member_id, diary_id)
* 비관적 락으로 동시성 제어
close #106
=> fix: 좋아요 데이터 동시성 제어

.github/workflows/pr_weekly_ci.yml, build.gradle
* `weekly/**`에 PR 요청 시 자동으로 테스트 커버리지 측정
close #111
=> feat: 테스트 커버리지 측정 자동화
